version: 2.1

orbs:
  node: circleci/node@4.1.0
  eks: circleci/aws-eks@1.0.3
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.4.0


jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            make install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: test
          command: |
            make doTest
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: install hadolint
          command: |
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
      - run:
          name: lint
          command: |
            make lint
  deploy:
    executor:
      name: aws-eks/python3
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: eksctl
          command: |
            kubectl version --short --client
            eksctl version
            kubectl get services
            kubectl get pods


workflows:
  lifecycle_workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - lint:
          requires: [test]
      - deploy:
          requires: [lint]
          filters:
            branches:
              only: [main]