version: 2.1

orbs:
  node: circleci/node@4.1.0
  eks: circleci/aws-eks@1.0.3
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0


jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            make install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: test
          command: |
            make doTest
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: install hadolint
          command: |
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
      - run:
          name: lint
          command: |
            make lint
  deploy:
    executor:
      name: aws-eks/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yum install -y tar gzip
      - attach_workspace:
          at: .
      - run:
          name: Install eksctl
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
      - run:
          name: eksctl
          command: |
            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
            kubectl version --short --client
            eksctl version
            kubectl get services
            kubectl get pods


workflows:
  lifecycle_workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - lint:
          requires: [test]
      - deploy:
          requires: [lint]
          filters:
            branches:
              only: [main]