apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacapstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacapstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacapstone
    spec:
      containers:
        - name: app
          image: seksky333/udacapstone
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: udacapstone
spec:
  selector:
    app: udacapstone
  ports:
    - port: 80
      targetPort: 49161
  type: LoadBalancer